/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Font converter for emWin version 5.22                       *
*        Compiled Jul  4 2013, 12:18:44                              *
*        (C) 1998 - 2013 Segger Microcontroller GmbH & Co. KG
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: CNFonts.c                                             *
* Font:        свт╡                                                  *
* Height:      21                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  21                                           *
* Range disabled:       0000 - FFFF                                  *
* Read pattern file: D:\HeatControl\SourceCode\HeatController\Project\STM32F10x_StdPeriph_OS_Console_EmWin\GUI_ToolSrc\WORDs_Unicode.txt*
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_FontCNFonts;

/* Start of unicode area <Basic Latin> */
GUI_CONST_STORAGE unsigned char acGUI_FontCNFonts_0025[ 28] = { /* code 0025, PERCENT SIGN */
  _XXX___X,X_______,
  XX_XX_XX,________,
  XX_XX_XX,________,
  XX_XXXX_,________,
  XX_XXXX_,________,
  XX_XXXX_,________,
  _XXXXX__,________,
  ____XXXX,X_______,
  ___XXXX_,XX______,
  ___XXXX_,XX______,
  __XX_XX_,XX______,
  __XX_XX_,XX______,
  __XX_XX_,XX______,
  _XX___XX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontCNFonts_002B[ 22] = { /* code 002B, PLUS SIGN */
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  XXXXXXXX,XX______,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________};

GUI_CONST_STORAGE unsigned char acGUI_FontCNFonts_002D[  2] = { /* code 002D, HYPHEN-MINUS */
  XXXXXXXX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontCNFonts_002E[  2] = { /* code 002E, FULL STOP */
  XXX_____,
  XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontCNFonts_002F[ 36] = { /* code 002F, SOLIDUS */
  ________,XX______,
  _______X,X_______,
  _______X,X_______,
  ______XX,X_______,
  ______XX,________,
  ______XX,________,
  _____XX_,________,
  _____XX_,________,
  ____XX__,________,
  ____XX__,________,
  ___XX___,________,
  ___XX___,________,
  __XX____,________,
  __XX____,________,
  _XXX____,________,
  _XX_____,________,
  _XX_____,________,
  XX______,________};

GUI_CONST_STORAGE unsigned char acGUI_FontCNFonts_0030[ 28] = { /* code 0030, DIGIT ZERO */
  __XXXXX_,________,
  _XX___XX,________,
  _XX___XX,________,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  _XX___XX,________,
  _XX___XX,________,
  __XXXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontCNFonts_0031[ 14] = { /* code 0031, DIGIT ONE */
  __XX____,
  XXXX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  XXXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontCNFonts_0032[ 28] = { /* code 0032, DIGIT TWO */
  _XXXXXX_,________,
  XX____XX,________,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  ______XX,________,
  ______XX,________,
  _____XX_,________,
  ____XX__,________,
  ___XX___,________,
  __XX____,________,
  _XX____X,X_______,
  XX_____X,X_______,
  XXXXXXXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontCNFonts_0033[ 28] = { /* code 0033, DIGIT THREE */
  _XXXXX__,________,
  XX___XX_,________,
  XX____XX,________,
  XX____XX,________,
  ______XX,________,
  _____XX_,________,
  ___XXXX_,________,
  ______XX,________,
  _______X,X_______,
  _______X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX____XX,________,
  _XXXXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontCNFonts_0034[ 30] = { /* code 0034, DIGIT FOUR */
  ______XX,________,
  _____XXX,________,
  ____XXXX,________,
  ____XXXX,________,
  ___XXXXX,________,
  __XX_XXX,________,
  __XX_XXX,________,
  _XX__XXX,________,
  XX___XXX,________,
  XX___XXX,________,
  _XXXXXXX,X_______,
  _____XXX,________,
  _____XXX,________,
  _____XXX,________,
  ___XXXXX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontCNFonts_0035[ 28] = { /* code 0035, DIGIT FIVE */
  _XXXXXXX,X_______,
  _XX_____,________,
  _XX_____,________,
  _XX_____,________,
  _XX_____,________,
  _XXXXXX_,________,
  _XXX__XX,________,
  _XX____X,X_______,
  _______X,X_______,
  _______X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX____XX,________,
  _XXXXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontCNFonts_0036[ 28] = { /* code 0036, DIGIT SIX */
  ___XXXXX,________,
  __XX___X,X_______,
  _XX____X,X_______,
  _XX_____,________,
  XX______,________,
  XXXXXXX_,________,
  XXX___XX,________,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  _XX____X,X_______,
  _XX___XX,________,
  __XXXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontCNFonts_0037[ 28] = { /* code 0037, DIGIT SEVEN */
  XXXXXXXX,X_______,
  XX____XX,________,
  XX___XX_,________,
  _____XX_,________,
  ____XX__,________,
  ____XX__,________,
  ___XX___,________,
  ___XX___,________,
  __XX____,________,
  __XX____,________,
  __XX____,________,
  __XX____,________,
  __XX____,________,
  __XX____,________};

GUI_CONST_STORAGE unsigned char acGUI_FontCNFonts_0038[ 28] = { /* code 0038, DIGIT EIGHT */
  __XXXXX_,________,
  _XX___XX,________,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  _XX___XX,________,
  __XXXXX_,________,
  _XX___XX,________,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  _XX___XX,________,
  __XXXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontCNFonts_0039[ 28] = { /* code 0039, DIGIT NINE */
  __XXXXX_,________,
  _XX___XX,________,
  XX____XX,________,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  _XX___XX,X_______,
  __XXXXXX,X_______,
  _______X,X_______,
  ______XX,________,
  XX____XX,________,
  XX___XX_,________,
  _XXXXX__,________};

GUI_CONST_STORAGE unsigned char acGUI_FontCNFonts_003A[ 10] = { /* code 003A, COLON */
  XXX_____,
  XXX_____,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XXX_____,
  XXX_____};

/* Start of unicode area <CJK Unified Ideographs> */
GUI_CONST_STORAGE unsigned char acGUI_FontCNFonts_4E0D[ 57] = { /* code 4E0D */
  _XXXXXXX,XXXXXXXX,XXXXX___,
  ________,___XX___,________,
  ________,__XXX___,________,
  ________,__XX____,________,
  ________,_XXX____,________,
  ________,_XXX____,________,
  ________,XXXXXXX_,________,
  _______X,X_XX_XXX,________,
  ______XX,__XX__XX,X_______,
  ____XXX_,__XX___X,XX______,
  ___XXX__,__XX____,XXX_____,
  _XXX____,__XX____,_XXX____,
  ________,__XX____,__XXX___,
  ________,__XX____,________,
  ________,__XX____,________,
  ________,__XX____,________,
  ________,__XX____,________,
  ________,__XX____,________,
  ________,__XX____,________};

GUI_CONST_STORAGE unsigned char acGUI_FontCNFonts_4F4D[ 60] = { /* code 4F4D */
  ________,________,________,
  _____XX_,____XX__,________,
  ____XX__,____XX__,________,
  ____XX__,____XXX_,________,
  ____XXXX,XXXXXXXX,XXXXX___,
  ___XX___,________,________,
  ___XX___,XX______,_XX_____,
  __XXX___,XX______,_XX_____,
  __XXX___,XX______,XXX_____,
  _XXXX___,XX______,XX______,
  XX_XX___,_XX_____,XX______,
  ___XX___,_XX_____,XX______,
  ___XX___,_XX_____,XX______,
  ___XX___,_XX____X,X_______,
  ___XX___,_XX____X,X_______,
  ___XX___,__XX___X,X_______,
  ___XX___,__XX__XX,X_______,
  ___XX___,______XX,________,
  ___XXXXX,XXXXXXXX,XXXXX___,
  ___XX___,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontCNFonts_4FDD[ 60] = { /* code 4FDD */
  ____XX__,________,________,
  ____XX_X,XXXXXXXX,XXX_____,
  ____XX_X,X_______,_XXX____,
  ____XX_X,X_______,__XX____,
  ___XX__X,X_______,__XX____,
  ___XX__X,X_______,__XX____,
  ___XX__X,X_______,__XX____,
  __XXX__X,XXXXXXXX,XXX_____,
  __XXX___,____XX__,________,
  _XXXX___,____XX__,________,
  _XXXX___,____XX__,________,
  ___XXXXX,XXXXXXXX,XXXXX___,
  ___XX___,___XXXX_,________,
  ___XX___,__XXXXXX,________,
  ___XX___,__XXXX_X,X_______,
  ___XX___,_XX_XX_X,XX______,
  ___XX__X,XX__XX__,_XX_____,
  ___XX_XX,X___XX__,__XXX___,
  ___XXXX_,____XX__,___XX___,
  ___XX___,____XX__,________};

GUI_CONST_STORAGE unsigned char acGUI_FontCNFonts_503C[ 60] = { /* code 503C */
  ____XX__,________,________,
  ____XX__,____XX__,________,
  ____XX__,____XX__,________,
  ___XXXXX,XXXXXXXX,XXXXX___,
  ___XX___,____XX__,________,
  ___XX___,____XX__,________,
  ___XX___,XXXXXXXX,XX______,
  __XXX__X,XX______,_XX_____,
  __XXX__X,X_______,_XX_____,
  _XXXX__X,XXXXXXXX,XXX_____,
  _XXXX__X,X_______,_XX_____,
  ___XX__X,X_______,_XX_____,
  ___XX__X,XXXXXXXX,XXX_____,
  ___XX__X,X_______,_XX_____,
  ___XX__X,X_______,_XX_____,
  ___XX__X,XXXXXXXX,XXX_____,
  ___XX__X,X_______,_XX_____,
  ___XX__X,X_______,_XX_____,
  ___XXXXX,XXXXXXXX,XXXXX___,
  ___XX___,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontCNFonts_505C[ 60] = { /* code 505C */
  ____XX__,___XX___,________,
  ____XX__,___XXX__,________,
  ____XXXX,XXXXXXXX,XXXX____,
  ___XXX__,________,________,
  ___XX___,________,________,
  ___XX__X,XXXXXXXX,XXX_____,
  ___XX__X,X_______,_XX_____,
  __XXX__X,X_______,_XX_____,
  __XXX__X,XXXXXXXX,XXX_____,
  _XXXX___,________,________,
  _XXXX_XX,XXXXXXXX,XXXXX___,
  ___XXXXX,________,___XX___,
  ___XXXX_,________,___XX___,
  ___XXXXX,XXXXXXXX,XXXXX___,
  ___XX___,____XX__,________,
  ___XX___,____XX__,________,
  ___XX___,____XX__,________,
  ___XX___,____XX__,________,
  ___XX___,XXX_XX__,________,
  ___XX___,__XXX___,________};

GUI_CONST_STORAGE unsigned char acGUI_FontCNFonts_5173[ 60] = { /* code 5173 */
  ________,________,________,
  _____XX_,______XX,________,
  _____XX_,_____XX_,________,
  ______XX,____XXX_,________,
  _XXXXXXX,XXXXXXXX,XXX_____,
  ________,_XX_____,________,
  ________,_XX_____,________,
  ________,_XX_____,________,
  ________,_XX_____,________,
  XXXXXXXX,XXXXXXXX,XXX_____,
  ________,_XX_____,________,
  ________,XXXX____,________,
  ________,XXXX____,________,
  _______X,XX_XX___,________,
  _______X,X__XXX__,________,
  ______XX,____XXX_,________,
  _____XX_,_____XXX,________,
  ___XXX__,______XX,X_______,
  _XXX____,________,XXX_____,
  XX______,________,__XX____};

GUI_CONST_STORAGE unsigned char acGUI_FontCNFonts_51BB[ 60] = { /* code 51BB */
  ________,________,________,
  ________,___XX___,________,
  _XX_____,__XXX___,________,
  _XX___XX,XXXXXXXX,XXXX____,
  __XX____,__XX____,________,
  __XX____,_XX_____,________,
  __XXX___,_XX_XX__,________,
  ___XX___,XX__XX__,________,
  ___XX__X,XX__XX__,________,
  _______X,X___XX__,________,
  ____XXXX,XXXXXXXX,XXXX____,
  ___XXX__,____XX__,________,
  ___XX___,XX__XX_X,X_______,
  ___XX___,XX__XX_X,XX______,
  __XX___X,XX__XX__,XX______,
  __XX___X,X___XX__,_XX_____,
  _XX___XX,X___XX__,_XX_____,
  _XX__XXX,____XX__,__XX____,
  XX___XX_,_XX_XX__,__XX____,
  ________,_XXXXX__,________};

GUI_CONST_STORAGE unsigned char acGUI_FontCNFonts_5206[ 60] = { /* code 5206 */
  ________,____XX__,________,
  _______X,XX__XXX_,________,
  _______X,X____XX_,________,
  ______XX,X_____XX,________,
  ______XX,______XX,X_______,
  _____XX_,_______X,XX______,
  ____XXX_,________,XXX_____,
  ___XXX__,________,_XXX____,
  __XXXXXX,XXXXXXXX,XXXXX___,
  _XX_____,XX______,XX_XXX__,
  ________,XX______,XX______,
  ________,XX______,XX______,
  ________,XX______,XX______,
  _______X,X_______,XX______,
  _______X,X_______,XX______,
  ______XX,________,XX______,
  _____XXX,________,XX______,
  ____XXX_,________,XX______,
  __XXX___,__XXX__X,X_______,
  _XX_____,____XXXX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontCNFonts_524D[ 60] = { /* code 524D */
  _____XX_,______XX,________,
  _____XX_,_____XXX,________,
  ______XX,_____XX_,________,
  XXXXXXXX,XXXXXXXX,XXXX____,
  ________,________,________,
  ________,________,________,
  __XXXXXX,XXX_____,_XX_____,
  _XX_____,_XX_XX__,_XX_____,
  _XX_____,_XX_XX__,_XX_____,
  _XX_____,_XX_XX__,_XX_____,
  _XXXXXXX,XXX_XX__,_XX_____,
  _XX_____,_XX_XX__,_XX_____,
  _XX_____,_XX_XX__,_XX_____,
  _XX_____,_XX_XX__,_XX_____,
  _XXXXXXX,XXX_XX__,_XX_____,
  _XX_____,_XX_XX__,_XX_____,
  _XX_____,_XX_____,_XX_____,
  _XX_____,_XX_____,_XX_____,
  _XX__XX_,_XX__XX_,_XX_____,
  _XX___XX,XX____XX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontCNFonts_529B[ 60] = { /* code 529B */
  ________,________,________,
  ________,XX______,________,
  ________,XX______,________,
  ________,XX______,________,
  _XXXXXXX,XXXXXXXX,XXX_____,
  ________,XX______,_XX_____,
  ________,XX______,_XX_____,
  ________,XX______,_XX_____,
  ________,XX______,_XX_____,
  ________,XX______,_XX_____,
  ________,XX______,_XX_____,
  _______X,X_______,_XX_____,
  _______X,X_______,_XX_____,
  ______XX,________,_XX_____,
  ______XX,________,_XX_____,
  _____XX_,________,_XX_____,
  ____XXX_,________,_XX_____,
  ___XXX__,________,_XX_____,
  __XXX___,__XXXX_X,XX______,
  _XX_____,_____XXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontCNFonts_52A8[ 60] = { /* code 52A8 */
  ________,________,________,
  ________,______XX,________,
  ________,______XX,________,
  __XXXXXX,XXX___XX,________,
  ________,______XX,________,
  ________,___XXXXX,XXXXX___,
  ________,______XX,___XX___,
  ________,______XX,___XX___,
  _XXXXXXX,XXXX__XX,___XX___,
  _____XX_,______XX,___XX___,
  _____XX_,______XX,___XX___,
  ____XX__,_____XX_,___XX___,
  ____XX__,XX___XX_,___XX___,
  ____XX__,XX___XX_,___XX___,
  ____XX__,XX___XX_,___XX___,
  ___XX___,_XX_XX__,___XX___,
  ___XX__X,XXX_XX__,___XX___,
  __XXXXXX,_XXXXX__,__XX____,
  ________,_XXXX_XX,XXXX____,
  ________,__XX____,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontCNFonts_538B[ 54] = { /* code 538B */
  _XXXXXXX,XXXXXXXX,XXX_____,
  _XX_____,________,________,
  _XX_____,__XX____,________,
  _XX_____,__XX____,________,
  _XX_____,__XX____,________,
  _XX_____,__XX____,________,
  _XX_____,__XX____,________,
  _XX_XXXX,XXXXXXXX,XX______,
  _XX_____,__XX____,________,
  _XX_____,__XX_XX_,________,
  _XX_____,__XX_XXX,________,
  _XX_____,__XX__XX,________,
  _XX_____,__XX__XX,X_______,
  _XX_____,__XX___X,X_______,
  _XX_____,__XX____,________,
  _XX_____,__XX____,________,
  XX_XXXXX,XXXXXXXX,XXXX____,
  XX______,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontCNFonts_540E[ 57] = { /* code 540E */
  ________,_XXXXXXX,XX______,
  __XXXXXX,XX______,________,
  __XX____,________,________,
  __XX____,________,________,
  __XX____,________,________,
  __XXXXXX,XXXXXXXX,XXXX____,
  __XX____,________,________,
  __XX____,________,________,
  __XX__XX,XXXXXXXX,XX______,
  __XX_XXX,________,XX______,
  __XX_XX_,________,XX______,
  __XX_XX_,________,XX______,
  __XX_XX_,________,XX______,
  __XX_XX_,________,XX______,
  _XX__XX_,________,XX______,
  _XX__XX_,________,XX______,
  XXX__XX_,________,XX______,
  XX___XXX,XXXXXXXX,XX______,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontCNFonts_542F[ 60] = { /* code 542F */
  ________,_XX_____,________,
  ________,_XX_____,________,
  ________,__XX____,________,
  ___XXXXX,XXXXXXXX,XXX_____,
  __XX____,________,_XX_____,
  __XX____,________,_XX_____,
  __XX____,________,_XX_____,
  __XXXXXX,XXXXXXXX,XXX_____,
  __XX____,________,________,
  __XX____,________,________,
  __XX____,________,________,
  __XX_XXX,XXXXXXXX,XXXX____,
  __XX_XX_,________,__XX____,
  __XX_XX_,________,__XX____,
  __XX_XX_,________,__XX____,
  __XX_XX_,________,__XX____,
  _XXX_XX_,________,__XX____,
  _XX__XX_,________,__XX____,
  XXX__XX_,________,__XX____,
  ______XX,XXXXXXXX,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontCNFonts_5439[ 60] = { /* code 5439 */
  ________,_XX_____,________,
  ________,_XX_____,________,
  ________,_XX_____,________,
  XXXXXXX_,XXXXXXXX,XXXX____,
  XX___XX_,XX______,__XX____,
  XX___XX_,XX______,__XX____,
  XX___XX_,XX__XX__,__XX____,
  XX___XXX,X___XX__,_XX_____,
  XX___XXX,X___XX__,_XX_____,
  XX___XX_,____XX__,XX______,
  XX___XX_,____XX__,XX______,
  XX___XX_,___XXXX_,________,
  XX___XX_,___XXXX_,________,
  XX___XX_,___XXXXX,________,
  XX___XX_,__XX__XX,________,
  XX___XX_,_XXX__XX,X_______,
  XXXXXXX_,XXX____X,X_______,
  _______X,XX______,XX______,
  ______XX,X_______,_XXX____,
  _____XX_,________,__XX____};

GUI_CONST_STORAGE unsigned char acGUI_FontCNFonts_5B9A[ 60] = { /* code 5B9A */
  ________,_XX_____,________,
  ________,_XXX____,________,
  ________,__XX____,________,
  __XXXXXX,XXXXXXXX,XXXX____,
  __XX____,________,__XX____,
  __XX____,________,__XX____,
  __XXXXXX,XXXXXXXX,XXXX____,
  ________,__XX____,________,
  ________,__XX____,________,
  ____XX__,__XX____,________,
  ____XX__,__XX____,________,
  ____XX__,__XXXXXX,XXX_____,
  ____XX__,__XX____,________,
  ____XX__,__XX____,________,
  ___XXXX_,__XX____,________,
  ___XXXXX,__XX____,________,
  __XXX__X,X_XX____,________,
  __XX____,XXXX____,________,
  _XXX____,__XXXXXX,________,
  _XX_____,_______X,XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontCNFonts_5E38[ 60] = { /* code 5E38 */
  ________,_XX_____,________,
  ___XX___,_XX____X,X_______,
  ____XX__,_XX___XX,X_______,
  _____XX_,_XX___XX,________,
  XXXXXXXX,XXXXXXXX,XXXX____,
  XX______,________,__XX____,
  XX__XXXX,XXXXXXXX,__XX____,
  XX_XXX__,_______X,XXXX____,
  ___XX___,_______X,XXX_____,
  ___XX___,_______X,X_______,
  ____XXXX,XXXXXXXX,________,
  ________,_XX_____,________,
  ___XXXXX,XXXXXXXX,XX______,
  __XX____,_XX_____,XXX_____,
  __XX____,_XX_____,_XX_____,
  __XX____,_XX_____,_XX_____,
  __XX____,_XX_____,_XX_____,
  __XX____,_XX_____,_XX_____,
  __XX____,_XX__XXX,XX______,
  ________,_XX_____,________};

GUI_CONST_STORAGE unsigned char acGUI_FontCNFonts_5E74[ 60] = { /* code 5E74 */
  _____XX_,________,________,
  _____XX_,________,________,
  ____XXXX,XXXXXXXX,XXX_____,
  ____XX__,__XX____,________,
  ___XX___,__XX____,________,
  __XX____,__XX____,________,
  _XXX____,__XX____,________,
  XXX_____,__XX____,________,
  ____XXXX,XXXXXXXX,XXX_____,
  ___XX___,__XX____,________,
  ___XX___,__XX____,________,
  ___XX___,__XX____,________,
  ___XX___,__XX____,________,
  ___XX___,__XX____,________,
  XXXXXXXX,XXXXXXXX,XXXX____,
  ________,__XX____,________,
  ________,__XX____,________,
  ________,__XX____,________,
  ________,__XX____,________,
  ________,__XX____,________};

GUI_CONST_STORAGE unsigned char acGUI_FontCNFonts_5EA6[ 60] = { /* code 5EA6 */
  ________,________,________,
  ________,__XX____,________,
  ___XXXXX,XXXXXXXX,XXXXX___,
  __XX___X,X_____XX,________,
  __XX___X,X_____XX,________,
  __XX___X,X_____XX,________,
  __XXXXXX,XXXXXXXX,XXXX____,
  __XX___X,X_____XX,________,
  __XX___X,X_____XX,________,
  __XX___X,XXXXXXXX,________,
  __XX____,________,________,
  __XX____,________,________,
  __XXXXXX,XXXXXXXX,XXX_____,
  __XX__XX,X______X,XX______,
  __XX___X,XX____XX,X_______,
  __XX____,XXX_XXX_,________,
  __XX____,__XXXX__,________,
  _XX_____,XXXXXXX_,________,
  _XX_XXXX,X____XXX,XX______,
  _XXXX___,________,_XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontCNFonts_5F00[ 57] = { /* code 5F00 */
  __XXXXXX,XXXXXXXX,XXXX____,
  ______XX,______XX,________,
  ______XX,______XX,________,
  ______XX,______XX,________,
  ______XX,______XX,________,
  ______XX,______XX,________,
  ______XX,______XX,________,
  ______XX,______XX,________,
  _XXXXXXX,XXXXXXXX,XXXXX___,
  ______XX,______XX,________,
  ______XX,______XX,________,
  _____XX_,______XX,________,
  _____XX_,______XX,________,
  _____XX_,______XX,________,
  _____XX_,______XX,________,
  _____XX_,______XX,________,
  ____XX__,______XX,________,
  ___XXX__,______XX,________,
  ___XX___,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontCNFonts_5F15[ 60] = { /* code 5F15 */
  ________,________,________,
  _XXXXXXX,XXXXX___,_XX_____,
  ________,___XX___,_XX_____,
  ________,___XX___,_XX_____,
  ________,___XX___,_XX_____,
  ________,___XX___,_XX_____,
  __XXXXXX,XXXX____,_XX_____,
  __XX____,________,_XX_____,
  _XX_____,________,_XX_____,
  _XX_____,________,_XX_____,
  _XX_____,________,_XX_____,
  __XXXXXX,XXXX____,_XX_____,
  ________,__XXX___,_XX_____,
  ________,___XX___,_XX_____,
  ________,___XX___,_XX_____,
  ________,___XX___,_XX_____,
  ________,__XX____,_XX_____,
  ________,__XX____,_XX_____,
  __XXXX__,_XXX____,_XX_____,
  ____XXXX,XX______,_XX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontCNFonts_5F85[ 60] = { /* code 5F85 */
  ________,____XX__,________,
  _____XX_,____XX__,________,
  ____XX__,____XX__,________,
  ___XXX_X,XXXXXXXX,XXXX____,
  ___XX___,____XX__,________,
  __XX____,____XX__,________,
  _XX__XX_,____XX__,________,
  _____XXX,XXXXXXXX,XXXX____,
  ____XX__,________,________,
  ___XXX__,________,XX______,
  ___XX___,________,XX______,
  __XXX_XX,XXXXXXXX,XXXXX___,
  _XXXX___,________,XX______,
  ___XX___,XXX_____,XX______,
  ___XX___,_XX_____,XX______,
  ___XX___,__XX____,XX______,
  ___XX___,___XX___,XX______,
  ___XX___,________,XX______,
  ___XX___,____XXXX,XX______,
  ________,_____XXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontCNFonts_6001[ 60] = { /* code 6001 */
  ________,__XX____,________,
  ________,__XX____,________,
  ________,__XX____,________,
  _XXXXXXX,XXXXXXXX,XXXXX___,
  ________,_XXXX___,________,
  ________,XXXXXX__,________,
  _______X,XX__XXX_,________,
  ______XX,XXX__XXX,________,
  ____XXX_,__XX___X,XX______,
  _XXXX___,__XXX___,_XXXX___,
  ________,___XX___,________,
  ________,__XX____,________,
  ___XX__X,X_XX____,XX______,
  ___XX__X,X__XX___,_XX_____,
  ___XX__X,X__XX___,_XX_____,
  __XXX__X,X___XX_X,X_XX____,
  __XX___X,X___XX_X,X_XX____,
  __XX___X,X______X,X__XX___,
  _XX____X,X_____XX,X__XX___,
  _______X,XXXXXXXX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontCNFonts_62A5[ 60] = { /* code 62A5 */
  ________,________,________,
  ____XX__,__XXXXXX,XX______,
  ____XX__,_XX_____,_XX_____,
  ____XX__,_XX_____,_XX_____,
  ____XX__,_XX_____,_XX_____,
  _XXXXXXX,XXX_____,_XX_____,
  ____XX__,_XX___XX,XXX_____,
  ____XX__,_XX_____,________,
  ____XX__,_XXXXXXX,XXX_____,
  ____XX__,_XXX____,__XX____,
  ____XXXX,_XXXX___,_XX_____,
  ____XXX_,_XXXX___,_XX_____,
  __XXXX__,_XX_XX__,XXX_____,
  _XX_XX__,_XX_XX__,XX______,
  ____XX__,_XX__XXX,X_______,
  ____XX__,_XX___XX,X_______,
  ____XX__,_XX__XXX,X_______,
  ____XX__,_XX_XXX_,XXX_____,
  _XXXXX__,_XXXX___,__XXX___,
  ___XX___,_XX_____,________};

GUI_CONST_STORAGE unsigned char acGUI_FontCNFonts_6599[ 60] = { /* code 6599 */
  ____XX__,________,_XX_____,
  ____XX__,________,_XX_____,
  _XX_XX__,XXXXX___,_XX_____,
  _XX_XX__,XX__XX__,_XX_____,
  __XXXX_X,XX___XX_,_XX_____,
  __XXXX_X,X_____XX,_XX_____,
  __XXXX_X,X______X,XXX_____,
  ____XX_X,X_XX____,_XX_____,
  ____XX__,__XXX___,_XX_____,
  XXXXXXXX,XX_XXX__,_XX_____,
  ____XXX_,____XXX_,_XX_____,
  ____XXXX,_____XXX,_XX_____,
  ___XXXXX,X_____XX,_XX_____,
  ___XXX_X,X_______,_XX_____,
  __XXXX__,XX______,_XXXX___,
  _XXXXX__,_XXXXXXX,XXX_____,
  _XX_XX__,________,_XX_____,
  ____XX__,________,_XX_____,
  ____XX__,________,_XX_____,
  ____XX__,________,_XX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontCNFonts_65E5[ 34] = { /* code 65E5 */
  _XXXXXXX,XXXXXXXX,
  XX______,______XX,
  XX______,______XX,
  XX______,______XX,
  XX______,______XX,
  XX______,______XX,
  XX______,______XX,
  XXXXXXXX,XXXXXXXX,
  XX______,______XX,
  XX______,______XX,
  XX______,______XX,
  XX______,______XX,
  XX______,______XX,
  XX______,______XX,
  XX______,______XX,
  XXX_____,______XX,
  _XXXXXXX,XXXXXXXX};

GUI_CONST_STORAGE unsigned char acGUI_FontCNFonts_65F6[ 57] = { /* code 65F6 */
  ________,______XX,________,
  XXXXXX__,______XX,________,
  XX__XX__,______XX,________,
  XX__XXXX,XXXXXXXX,XXX_____,
  XX__XX__,______XX,________,
  XX__XX__,______XX,________,
  XX__XX__,______XX,________,
  XX__XX_X,X_____XX,________,
  XX__XX__,XX____XX,________,
  XXXXXX__,_XX___XX,________,
  XX__XX__,__XX__XX,________,
  XX__XX__,__XXX_XX,________,
  XX__XX__,___XX_XX,________,
  XX__XX__,______XX,________,
  XX__XX__,______XX,________,
  XX__XX__,______XX,________,
  XX__XX__,______XX,________,
  XXXXXX__,_XXXXXXX,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontCNFonts_661F[ 57] = { /* code 661F */
  ___XXXXX,XXXXXXXX,X_______,
  __XXX___,________,XX______,
  __XX____,________,XX______,
  __XX____,________,XX______,
  __XXXXXX,XXXXXXXX,XX______,
  __XX____,________,XX______,
  __XXX___,________,XX______,
  ___XXXXX,XXXXXXXX,X_______,
  ____XX__,_XX_____,________,
  ____XX__,_XX_____,________,
  ___XXXXX,XXXXXXXX,XXX_____,
  __XX____,_XX_____,________,
  _XX_____,_XX_____,________,
  ________,_XX_____,________,
  ___XXXXX,XXXXXXXX,XX______,
  ________,_XX_____,________,
  ________,_XX_____,________,
  ________,_XX_____,________,
  _XXXXXXX,XXXXXXXX,XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontCNFonts_6708[ 57] = { /* code 6708 */
  ____XXXX,XXXXXXXX,XX______,
  ____XX__,________,_XX_____,
  ____XX__,________,_XX_____,
  ____XX__,________,_XX_____,
  ____XX__,________,_XX_____,
  ____XXXX,XXXXXXXX,XXX_____,
  ____XX__,________,_XX_____,
  ____XX__,________,_XX_____,
  ____XX__,________,_XX_____,
  ____XX__,________,_XX_____,
  ____XXXX,XXXXXXXX,XXX_____,
  ____XX__,________,_XX_____,
  ____XX__,________,_XX_____,
  ____XX__,________,_XX_____,
  ___XX___,________,_XX_____,
  ___XX___,________,_XX_____,
  __XXX___,________,_XX_____,
  __XX____,___XXX__,XX______,
  _XX_____,_____XXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontCNFonts_671F[ 57] = { /* code 671F */
  __XX___X,X_______,________,
  __XX___X,X__XXXXX,XXX_____,
  XXXXXXXX,XXXXX___,_XX_____,
  __XX___X,X__XX___,_XX_____,
  __XX___X,X__XX___,_XX_____,
  __XXXXXX,X__XX___,_XX_____,
  __XX___X,X__XXXXX,XXX_____,
  __XX___X,X__XX___,_XX_____,
  __XX___X,X__XX___,_XX_____,
  __XXXXXX,X__XX___,_XX_____,
  __XX___X,X__XX___,_XX_____,
  __XX___X,X__XXXXX,XXX_____,
  __XX___X,X__XX___,_XX_____,
  XXXXXXXX,XXXXX___,_XX_____,
  ___XX_XX,___XX___,_XX_____,
  __XXX_XX,X__XX___,_XX_____,
  __XX___X,X_XX____,_XX_____,
  _XX_____,XXXX____,_XX_____,
  _XX_____,XXXX__XX,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontCNFonts_673A[ 60] = { /* code 673A */
  ________,________,________,
  ____XX__,___XXXXX,________,
  ____XX__,__XX___X,X_______,
  ____XX__,__XX___X,X_______,
  ____XX__,__XX___X,X_______,
  _XXXXXXX,X_XX___X,X_______,
  ____XX__,__XX___X,X_______,
  ____XXX_,__XX___X,X_______,
  ___XXXXX,__XX___X,X_______,
  ___XXXXX,__XX___X,X_______,
  __XXXXXX,X_XX___X,X_______,
  __XXXX_X,XXX____X,X_______,
  _XXXXX__,_XX____X,X_______,
  _XX_XX__,_XX____X,X_______,
  _XX_XX__,_XX____X,X__XX___,
  ____XX__,_XX____X,X__XX___,
  ____XX__,XX_____X,X__XX___,
  ____XX__,XX_____X,X__XX___,
  ____XX_X,X_______,XXXXX___,
  ____XXXX,X_______,________};

GUI_CONST_STORAGE unsigned char acGUI_FontCNFonts_6B62[ 54] = { /* code 6B62 */
  ________,__XX____,________,
  ________,__XX____,________,
  ________,__XX____,________,
  ___XX___,__XX____,________,
  ___XX___,__XX____,________,
  ___XX___,__XX____,________,
  ___XX___,__XXXXXX,XXX_____,
  ___XX___,__XX____,________,
  ___XX___,__XX____,________,
  ___XX___,__XX____,________,
  ___XX___,__XX____,________,
  ___XX___,__XX____,________,
  ___XX___,__XX____,________,
  ___XX___,__XX____,________,
  ___XX___,__XX____,________,
  ___XX___,__XX____,________,
  ___XX___,__XX____,________,
  XXXXXXXX,XXXXXXXX,XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontCNFonts_6B63[ 51] = { /* code 6B63 */
  __XXXXXX,XXXXXXXX,XXXXX___,
  ________,__XX____,________,
  ________,__XX____,________,
  ________,__XX____,________,
  ________,__XX____,________,
  ____XX__,__XX____,________,
  ____XX__,__XX____,________,
  ____XX__,__XX____,________,
  ____XX__,__XXXXXX,XXXX____,
  ____XX__,__XX____,________,
  ____XX__,__XX____,________,
  ____XX__,__XX____,________,
  ____XX__,__XX____,________,
  ____XX__,__XX____,________,
  ____XX__,__XX____,________,
  ____XX__,__XX____,________,
  _XXXXXXX,XXXXXXXX,XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontCNFonts_6C34[ 60] = { /* code 6C34 */
  ________,________,________,
  ________,_XX_____,________,
  ________,_XX_____,________,
  ________,_XX_____,_XX_____,
  ________,_XX_____,XXX_____,
  XXXXXXXX,XXX____X,XX______,
  _______X,XXXX__XX,X_______,
  _______X,XXXX_XXX,________,
  _______X,XXXXXXX_,________,
  _______X,XXXXX___,________,
  ______XX,_XX_XX__,________,
  ______XX,_XX_XXX_,________,
  _____XX_,_XX__XX_,________,
  ____XX__,_XX___XX,________,
  __XXX___,_XX____X,X_______,
  XXXX____,_XX_____,XX______,
  ________,_XX_____,_XX_____,
  ________,_XX_____,__XX____,
  ____XXXX,_XX_____,________,
  ______XX,XXX_____,________};

GUI_CONST_STORAGE unsigned char acGUI_FontCNFonts_6CF5[ 57] = { /* code 6CF5 */
  _XXXXXXX,XXXXXXXX,XXX_____,
  ______XX,________,________,
  ______XX,________,________,
  _____XXX,XXXXXXXX,X_______,
  ____XX__,_______X,XX______,
  __XXXX__,________,XX______,
  XXX_XX__,________,XX______,
  ____XXXX,XXXXXXXX,XX______,
  ________,_XX_____,________,
  ________,_XX_____,XXX_____,
  _XXXXXXX,XXX____X,X_______,
  _______X,XXXX_XXX,________,
  ______XX,_XXXXXX_,________,
  ______XX,_XX_XX__,________,
  _____XX_,_XX__XXX,________,
  ___XXX__,_XX___XX,X_______,
  _XXX____,_XX_____,XXX_____,
  XX____XX,_XX_____,__XX____,
  _______X,XXX_____,________};

GUI_CONST_STORAGE unsigned char acGUI_FontCNFonts_6E29[ 57] = { /* code 6E29 */
  __XX___X,XXXXXXXX,XXX_____,
  __XXX__X,X_______,_XX_____,
  ___XXX_X,X_______,_XX_____,
  ____XXXX,X_______,_XX_____,
  _______X,XXXXXXXX,XXX_____,
  _XX____X,X_______,_XX_____,
  __XX___X,X_______,_XX_____,
  ___XXX_X,XXXXXXXX,XXX_____,
  ____XX__,________,________,
  ________,________,________,
  ____XX__,________,________,
  ____XXXX,XXXXXXXX,XXXX____,
  ____XXXX,__XX__XX,__XX____,
  ___XX_XX,__XX__XX,__XX____,
  ___XX_XX,__XX__XX,__XX____,
  __XXX_XX,__XX__XX,__XX____,
  __XX__XX,__XX__XX,__XX____,
  _XXX__XX,__XX__XX,__XX____,
  _XX__XXX,XXXXXXXX,XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontCNFonts_6EDE[ 60] = { /* code 6EDE */
  ________,________,________,
  _XXX____,XX__XX__,XX______,
  __XXX___,XX__XX__,XX______,
  ___XXX__,XX__XX__,XX______,
  _____XXX,XXXXXXXX,XXXXX___,
  ________,XX__XX__,XX______,
  _XX_____,XX__XX__,XX______,
  _XXX____,________,________,
  __XXX_XX,XXXXXXXX,XXXXX___,
  ___XXXXX,____XX__,___XX___,
  ______XX,____XX__,___XX___,
  ____XXXX,XXXXXXXX,XX_XX___,
  ___XXX_X,XX__XX__,_XX_____,
  ___XX__X,X___XX__,_XX_____,
  ___XX__X,X___XX__,_XX_____,
  ___XX__X,X___XX__,_XX_____,
  __XX___X,X___XX__,_XX_____,
  __XX___X,X___XX__,_XX_____,
  _XX_____,____XX_X,XXX_____,
  ________,____XX__,________};

GUI_CONST_STORAGE unsigned char acGUI_FontCNFonts_706B[ 60] = { /* code 706B */
  ________,_XX_____,________,
  ________,_XX_____,________,
  ____XX__,_XX_____,XX______,
  ____XX__,_XX_____,XX______,
  ____XX__,_XX_____,XX______,
  ____XX__,_XX____X,X_______,
  ___XX___,_XX____X,X_______,
  ___XX___,_XX____X,X_______,
  ___XX___,_XX____X,X_______,
  __XX____,_XX___XX,________,
  __XX____,_XX___XX,________,
  ________,_XXX____,________,
  ________,XXXX____,________,
  _______X,XX_XX___,________,
  _______X,X___XX__,________,
  ______XX,____XXX_,________,
  _____XX_,_____XXX,________,
  ___XXX__,_______X,X_______,
  _XXX____,________,XXX_____,
  XXX_____,________,__XX____};

GUI_CONST_STORAGE unsigned char acGUI_FontCNFonts_70B9[ 60] = { /* code 70B9 */
  ________,________,________,
  ________,XX______,________,
  ________,XX______,________,
  ________,XXXXXXXX,XXXX____,
  ________,XX______,________,
  ________,XX______,________,
  ___XXXXX,XXXXXXXX,________,
  __XXX___,_______X,XX______,
  __XX____,________,XX______,
  __XX____,________,XX______,
  __XX____,________,XX______,
  __XX____,________,XX______,
  __XX____,________,XX______,
  __XXXXXX,XXXXXXXX,X_______,
  ________,________,________,
  __XX__XX,___XX___,XX______,
  __XX__XX,____XX__,_XX_____,
  _XX____X,X___XX__,_XX_____,
  _XX____X,X___XX__,__XX____,
  XX_____X,X___XX__,__XX____};

GUI_CONST_STORAGE unsigned char acGUI_FontCNFonts_70ED[ 60] = { /* code 70ED */
  ________,____XX__,________,
  _____XX_,____XX__,________,
  _____XX_,____XX__,________,
  _XXXXXXX,XXXXXXXX,XX______,
  _____XX_,____XX__,XX______,
  _____XX_,____XX__,XX______,
  _____XXX,X_XXXX__,XX______,
  ____XXX_,__XXXX__,XX______,
  __XXXXX_,___XXX__,XX______,
  _XX__XX_,___XXX__,_XXXX___,
  _____XX_,___XXX__,_XXXX___,
  _____XX_,__XX_XX_,_XXXX___,
  _____XX_,_XXX_XX_,_XXXX___,
  __XXXXX_,_XX___XX,_XXXX___,
  ____XX__,XX______,__XX____,
  ____XX_X,X___XX__,XXX_____,
  ___XX___,XX__XXX_,_XX_____,
  ___XX___,XX___XX_,__XX____,
  __XX____,XX___XX_,__XX____,
  _XX_____,XX____XX,___XX___};

GUI_CONST_STORAGE unsigned char acGUI_FontCNFonts_72B6[ 60] = { /* code 72B6 */
  ________,________,________,
  ______XX,_____XXX,X_______,
  ______XX,_____XX_,XX______,
  _XX___XX,_____XX_,XXX_____,
  _XXX__XX,_____XX_,_XX_____,
  __XXX_XX,_____XX_,_XX_____,
  ___XX_XX,XXXXXXXX,XXXXX___,
  ____XXXX,_____XX_,________,
  ______XX,____XXX_,________,
  ______XX,____XXXX,________,
  ______XX,____XXXX,________,
  ____XXXX,____XXXX,________,
  ____XXXX,___XX__X,X_______,
  ___XX_XX,___XX__X,X_______,
  __XX__XX,___XX___,XX______,
  _XXX__XX,__XX____,XX______,
  _XX___XX,_XXX____,_XX_____,
  ______XX,_XX_____,_XXX____,
  ______XX,XX______,__XX____,
  ______XX,X_______,___XX___};

GUI_CONST_STORAGE unsigned char acGUI_FontCNFonts_79D2[ 60] = { /* code 79D2 */
  ________,________,________,
  ______XX,X____XX_,________,
  __XXXXX_,_____XX_,________,
  ____XX__,__XX_XX_,XXX_____,
  ____XX__,__XX_XX_,_XX_____,
  ____XX__,__XX_XX_,_XX_____,
  _XXXXXXX,XXX__XX_,__XX____,
  ____XX__,_XX__XX_,__XX____,
  ____XXX_,_XX__XX_,__XX____,
  ___XXXX_,XXX__XX_,___XX___,
  ___XXXXX,XX___XX_,_XXXX___,
  __XXXXXX,XX___XX_,_XXXX___,
  __XXXX__,_____XX_,_XX_____,
  _XX_XX__,_____XX_,_XX_____,
  XXX_XX__,_____XX_,XX______,
  ____XX__,________,XX______,
  ____XX__,_______X,X_______,
  ____XX__,_____XXX,________,
  ____XX__,___XXXX_,________,
  ____XX__,XXXX____,________};

GUI_CONST_STORAGE unsigned char acGUI_FontCNFonts_7CFB[ 60] = { /* code 7CFB */
  ________,________,________,
  _XXXXXXX,XXXXXXXX,X_______,
  ________,XX______,________,
  _______X,X_______,________,
  _____XXX,_____XX_,________,
  ____XXX_,____XX__,________,
  ___XXXXX,XXXXX___,________,
  ________,_XXX__XX,________,
  _______X,XX_____X,X_______,
  _____XXX,_______X,XX______,
  ___XXX__,_____XXX,XX______,
  __XXXXXX,XXXXXX__,XXX_____,
  ____XX__,_XX__XX_,_XX_____,
  ____XX__,_XX__XX_,_XX_____,
  ___XXX__,_XX___XX,________,
  ___XX___,_XX___XX,X_______,
  __XX____,_XX____X,X_______,
  _XXX____,_XX_____,XX______,
  _XX__XX_,_XX_____,XX______,
  ______XX,XXX_____,________};

GUI_CONST_STORAGE unsigned char acGUI_FontCNFonts_7EDF[ 60] = { /* code 7EDF */
  ________,________,________,
  ________,_____XX_,________,
  ____XX__,_____XX_,________,
  ____XX__,XXXXXXXX,XXXXX___,
  ___XX___,____XX__,________,
  ___XX__X,X__XX__X,XX______,
  __XX__XX,___XX___,XX______,
  __XX__XX,__XX____,XXX_____,
  _XXXXXX_,__XX____,_XX_____,
  _XXX_XX_,_XXXXXXX,XXX_____,
  ____XX__,_XXXX__X,X_XX____,
  ___XXX__,___XX__X,X_XX____,
  ___XX___,___XX__X,X_______,
  __XX_XXX,XX_XX__X,X_______,
  _XXXXX__,___XX__X,X__XX___,
  ________,__XX___X,X__XX___,
  ________,XXXX___X,X__XX___,
  ____XXXX,XXX____X,X__XX___,
  _XXXX___,XX_____X,X_XXX___,
  _______X,X_______,XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontCNFonts_7F6E[ 54] = { /* code 7F6E */
  ___XXXXX,XXXXXXXX,XXX_____,
  __XX___X,X___XX__,_XXX____,
  __XX___X,X___XX__,__XX____,
  __XX___X,X___XX__,__XX____,
  ___XXXXX,XXXXXXXX,XXX_____,
  ________,__XX____,________,
  _XXXXXXX,XXXXXXXX,XXXXX___,
  ________,_XX_____,________,
  ____XXXX,XXXXXXXX,XX______,
  ____XX__,________,XX______,
  ____XX__,________,XX______,
  ____XXXX,XXXXXXXX,XX______,
  ____XX__,________,XX______,
  ____XXXX,XXXXXXXX,XX______,
  ____XX__,________,XX______,
  ____XXXX,XXXXXXXX,XX______,
  ____XX__,________,XX______,
  _XXXXXXX,XXXXXXXX,XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontCNFonts_884C[ 60] = { /* code 884C */
  ________,________,________,
  ____XX__,________,________,
  ____XX_X,XXXXXXXX,XXXX____,
  ___XXX__,________,________,
  ___XX___,________,________,
  __XX____,________,________,
  _XXX_XX_,________,________,
  ____XX_X,XXXXXXXX,XXXXX___,
  ____XX__,_______X,X_______,
  ___XXX__,_______X,X_______,
  ___XX___,_______X,X_______,
  __XXX___,_______X,X_______,
  _XXXX___,_______X,X_______,
  ___XX___,_______X,X_______,
  ___XX___,_______X,X_______,
  ___XX___,_______X,X_______,
  ___XX___,_______X,X_______,
  ___XX___,_______X,X_______,
  ___XX___,__XXX__X,X_______,
  ___XX___,____XXXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontCNFonts_8B66[ 60] = { /* code 8B66 */
  ___XX___,________,________,
  ___XX__X,X___XX__,________,
  XXXXXXXX,XXXXXXXX,XXXX____,
  __XXX__X,X__XXX__,XX______,
  __XXXXXX,XXXXXXX_,XX______,
  _XX_____,_XX__XXX,X_______,
  _XXXXXXX,_XX___XX,________,
  __XX__XX,_XX__XXX,XX______,
  __XXXXXX,_XX_XX__,XXXX____,
  _______X,XXXXX___,__XX____,
  ________,_XX_____,________,
  XXXXXXXX,XXXXXXXX,XXXX____,
  ________,________,________,
  ___XXXXX,XXXXXXXX,XX______,
  ________,________,________,
  ___XXXXX,XXXXXXXX,XX______,
  ___XXXXX,XXXXXXXX,X_______,
  __XXX___,________,XX______,
  __XXX___,________,XX______,
  ___XXXXX,XXXXXXXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontCNFonts_8BBE[ 57] = { /* code 8BBE */
  ________,___XXXXX,XX______,
  ___XX___,__XX____,XX______,
  ___XXX__,__XX____,XX______,
  ____XXX_,__XX____,XX______,
  _____XX_,__XX____,XX______,
  ________,_XXX____,XX______,
  _XXXXX__,XXX_____,XXXX____,
  ____XX__,________,________,
  ____XX__,_XXXXXXX,XXX_____,
  ____XX__,__XX____,_XX_____,
  ____XX__,___XX___,_XX_____,
  ____XX__,___XX___,XX______,
  ____XX__,___XXX_X,XX______,
  ____XX__,____XX_X,X_______,
  ____XX_X,X____XXX,________,
  ____XXXX,____XXXX,X_______,
  ____XXXX,___XXX_X,XX______,
  ____XX__,XXXX____,_XXX____,
  ________,XX______,___XX___};

GUI_CONST_STORAGE unsigned char acGUI_FontCNFonts_8D85[ 60] = { /* code 8D85 */
  _____XX_,________,________,
  _____XX_,________,________,
  _____XX_,__XXXXXX,XXXX____,
  __XXXXXX,XXX__XX_,___XX___,
  _____XX_,____XX__,___XX___,
  _____XX_,____XX__,___XX___,
  _____XX_,____XX__,__XX____,
  _XXXXXXX,XXXXX___,__XX____,
  _____XX_,__XXXXXX,XXXX____,
  __XX_XX_,_XXX____,XXX_____,
  __XX_XX_,___XXXXX,XXX_____,
  __XX_XX_,__XXX___,__XX____,
  __XX_XXX,XXXX____,__XX____,
  __XX_XX_,__XX____,__XX____,
  __XXXXX_,__XX____,__XX____,
  __XXXXX_,__XX____,__XX____,
  _XXXXXX_,__XXXXXX,XXXX____,
  _XX__XXX,________,________,
  _XX____X,XXX_____,________,
  ________,__XXXXXX,XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontCNFonts_8DB3[ 57] = { /* code 8DB3 */
  ____XXXX,XXXXXXXX,XX______,
  ___XX___,________,XXX_____,
  ___XX___,________,_XX_____,
  ___XX___,________,_XX_____,
  ___XX___,________,_XX_____,
  ___XX___,________,_XX_____,
  ___XX___,________,_XX_____,
  ____XXXX,XXXXXXXX,XX______,
  ____XX__,__XX____,________,
  ____XX__,__XX____,________,
  ____XX__,__XX____,________,
  ____XX__,__XX____,________,
  ____XX__,__XXXXXX,XXX_____,
  ___XXX__,__XX____,________,
  ___XXXX_,__XX____,________,
  ___XXXXX,__XX____,________,
  __XX__XX,X_XX____,________,
  _XX_____,XXXX____,________,
  _XX_____,__XXXXXX,XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontCNFonts_8FD0[ 57] = { /* code 8FD0 */
  _XXX___X,XXXXXXXX,XXX_____,
  __XXX___,________,________,
  ____XX__,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  _XXX__XX,XXXXXXXX,XXXX____,
  ___XXX__,___XX___,________,
  ____XX__,___XX___,________,
  ____XX__,__XX___X,X_______,
  ____XX__,__XX____,XX______,
  ____XX__,_XX_____,XX______,
  ____XX__,_XX_____,_XX_____,
  ____XX__,XX______,_XX_____,
  ____XX_X,XXXXXXXX,XXXX____,
  ___XXXX_,________,__XX____,
  ___XXXXX,________,________,
  _XXX___X,XX______,________,
  ________,_XXXXXXX,XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontCNFonts_8FDB[ 60] = { /* code 8FDB */
  ________,________,________,
  __XX____,__XX___X,X_______,
  ___XX___,__XX___X,X_______,
  ___XX___,__XX___X,X_______,
  ____XX_X,XXXXXXXX,XXXX____,
  ____XX__,__XX___X,X_______,
  ________,__XX___X,X_______,
  _XXXX___,__XX___X,X_______,
  ____XX__,__XX___X,X_______,
  ____XX__,__XX___X,X_______,
  ____XXXX,XXXXXXXX,XXXXX___,
  ____XX__,__XX___X,X_______,
  ____XX__,_XX____X,X_______,
  ____XX__,_XX____X,X_______,
  ____XX__,_XX____X,X_______,
  ____XXX_,XXX____X,X_______,
  ___XXXX_,XX_____X,X_______,
  __XXX_XX,X______X,X_______,
  _XXX___X,XXX_____,________,
  ________,__XXXXXX,XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontCNFonts_9001[ 57] = { /* code 9001 */
  _XX_____,________,XX______,
  __XX___X,XX_____X,X_______,
  __XX____,XXX___XX,X_______,
  ___XX___,_XXX_XXX,________,
  ___XX___,________,________,
  ______XX,XXXXXXXX,XXX_____,
  XXXXX___,___XX___,________,
  ___XX___,___XX___,________,
  ___XX___,___XX___,________,
  ___XXXXX,XXXXXXXX,XXXX____,
  ___XX___,___XX___,________,
  ___XX___,___XXXX_,________,
  ___XX___,__XX_XXX,________,
  ___XX___,_XXX__XX,X_______,
  ___XX___,XXX____X,XX______,
  ___XXXXX,X_______,XX______,
  __XXXXX_,________,________,
  _XX__XXX,X_______,________,
  XX_____X,XXXXXXXX,XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontCNFonts_95F4[ 60] = { /* code 95F4 */
  ________,________,________,
  _XX_____,________,________,
  _XXX__XX,XXXXXXXX,XX______,
  __XX____,________,XX______,
  ________,________,XX______,
  XX______,________,XX______,
  XX__XXXX,XXXXXX__,XX______,
  XX__XX__,____XX__,XX______,
  XX__XX__,____XX__,XX______,
  XX__XX__,____XX__,XX______,
  XX__XXXX,XXXXXX__,XX______,
  XX__XX__,____XX__,XX______,
  XX__XX__,____XX__,XX______,
  XX__XX__,____XX__,XX______,
  XX__XX__,____XX__,XX______,
  XX__XX__,____XX__,XX______,
  XX__XXXX,XXXXXX__,XX______,
  XX______,________,XX______,
  XX______,____XX__,XX______,
  XX______,_____XXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontCNFonts_9608[ 60] = { /* code 9608 */
  ________,________,________,
  __XX__XX,XXXXXXXX,XXX_____,
  ___XX___,________,_XX_____,
  ________,__XX_XX_,_XX_____,
  XX______,__XX_XXX,_XX_____,
  XX_XXXXX,XXXXXXXX,_XX_____,
  XX______,__XX___X,XXX_____,
  XX______,___XX__X,XXX_____,
  XX_XXXXX,XX_XX_XX,_XX_____,
  XX_XX___,_XXXX_XX,_XX_____,
  XX_XX___,_XXXXXX_,_XX_____,
  XX_XX___,_XXXXXX_,_XX_____,
  XX_XXXXX,XX__XX_X,XXX_____,
  XX______,____XX_X,XXX_____,
  XX_____X,XX_XXXXX,XXX_____,
  XX_XXXXX,__XX_XXX,XXX_____,
  XX______,XXX___XX,XXX_____,
  XX______,________,_XX_____,
  XX______,_____XXX,_XX_____,
  ________,_______X,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontCNFonts_9632[ 60] = { /* code 9632 */
  ________,________,________,
  _XXXXXX_,___XX___,________,
  _XX__XX_,____XX__,________,
  XX___XXX,XXXXXXXX,XXXX____,
  XX__XX__,__XX____,________,
  XX__XX__,__XX____,________,
  XX__XX__,__XX____,________,
  XX__XX__,__XX____,________,
  XX__XX__,__XXXXXX,XX______,
  XX___XX_,__XX____,_XX_____,
  XX___XX_,_XX_____,_XX_____,
  XX___XX_,_XX_____,_XX_____,
  XX___XX_,_XX_____,_XX_____,
  XXXXXXX_,_XX_____,XX______,
  XX______,XX______,XX______,
  XX______,XX______,XX______,
  XX_____X,X_______,XX______,
  XX____XX,________,XX______,
  XX___XX_,__XXXXXX,X_______,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontCNFonts_9636[ 60] = { /* code 9636 */
  ________,________,________,
  XXXXX___,__XXX___,________,
  XX_XX___,_XXXXX__,________,
  XX_XX___,XXX_XXX_,________,
  XX_XX___,XX___XX_,________,
  XX_XX__X,X_____XX,________,
  XX_XX_XX,_______X,X_______,
  XX_XXXX_,XX______,XX______,
  XX_XX___,XX___XX_,_XX_____,
  XX_XX___,XX___XX_,________,
  XX__XX__,XX___XX_,________,
  XX__XX__,XX___XX_,________,
  XX__XX__,XX___XX_,________,
  XXXXXX__,XX___XX_,________,
  XXXX___X,XX___XX_,________,
  XX_____X,X____XX_,________,
  XX____XX,X____XX_,________,
  XX____XX,_____XX_,________,
  XX___XX_,_____XX_,________,
  XX__XX__,_____XX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontCNFonts_9694[ 57] = { /* code 9694 */
  XXXXXXXX,XXXXXXXX,XXX_____,
  XX__XX__,________,________,
  XX_XX__X,XXXXXXXX,________,
  XX_XX_XX,X______X,X_______,
  XX_XX_XX,_______X,X_______,
  XXXX__XX,_______X,X_______,
  XXXX___X,XXXXXXXX,X_______,
  XX_XX___,________,________,
  XX_XX_XX,XXXXXXXX,XX______,
  XX__XXXX,XX___XX_,XX______,
  XX__XXXX,_XX__XX_,XX______,
  XX__XXXX,_XX__XX_,XX______,
  XXX_XXXX,_XX_XX__,XX______,
  XXXXX_XX,XXXXXXXX,XX______,
  XX____XX,___XX___,XX______,
  XX____XX,___XX___,XX______,
  XX____XX,___XX___,XX______,
  XX____XX,___XXXXX,XX______,
  XX______,______XX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontCNFonts_9884[ 57] = { /* code 9884 */
  __XXXXXX,XXXXXXXX,XXXXX___,
  ________,XX____XX,________,
  ________,XX____XX,________,
  __XX___X,X____XX_,________,
  ___XX_XX,__XXXXXX,XXXX____,
  ____XXX_,__XX____,__XX____,
  ____XX__,__XX____,__XX____,
  _____XX_,__XX__XX,__XX____,
  _XXXXXXX,XXXX__XX,__XX____,
  _____XX_,XXXX__XX,__XX____,
  _____XX_,XXXX__XX,__XX____,
  _____XXX,XXXX__XX,__XX____,
  _____XXX,X_XX_XX_,__XX____,
  _____XX_,__XX_XX_,__XX____,
  _____XX_,____XXXX,X_______,
  _____XX_,____XX__,XX______,
  _____XX_,___XX___,_XX_____,
  _XXXXX__,_XXX____,__XX____,
  ___XXX__,XX______,___XX___};

GUI_CONST_STORAGE unsigned char acGUI_FontCNFonts_98CE[ 57] = { /* code 98CE */
  __XXXXXX,XXXXXXXX,X_______,
  __XX____,________,XX______,
  _XX_____,_____XX_,XX______,
  _XX_XX__,____XXX_,XX______,
  _XX__XX_,____XX__,XX______,
  _XX___XX,____XX__,XX______,
  _XX___XX,X__XX___,XX______,
  _XX____X,XX_XX___,XX______,
  _XX_____,XXXX____,XX______,
  _XX_____,_XXX____,XX______,
  _XX_____,_XXX____,XX______,
  _XX_____,XXXXX___,XX______,
  _XX____X,X__XX___,XX______,
  _XX___XX,____XX__,XX______,
  _XX__XX_,_____XX_,XXXX____,
  _XX_XX__,_____XXX,XXXX____,
  XX_XX___,______XX,XXXX____,
  XX______,________,XXXX____,
  XX______,________,_XX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontCNFonts_9F13[ 60] = { /* code 9F13 */
  ________,________,________,
  _____XX_,_____XX_,________,
  _XXXXXXX,XX___XX_,________,
  _____XX_,__XXXXXX,XXX_____,
  _____XX_,_____XX_,________,
  _XXXXXXX,XX___XX_,________,
  ________,_____XX_,________,
  ___XXXXX,__XXXXXX,XX______,
  __XX___X,XX_XX___,_XX_____,
  _XX_____,XX_XX___,_XX_____,
  _XX_____,XX__XX__,XXX_____,
  _XX_____,XX__XX__,XX______,
  _XX_____,XX__XX__,XX______,
  __XXXXXX,XX___XXX,X_______,
  ________,_____XXX,X_______,
  __XX___X,X_____XX,________,
  ___XX__X,X____XXX,X_______,
  ___XX_XX,XX__XX_X,XX______,
  __XXXXXX,X_XXX___,XXX_____,
  XXXX____,_XXX____,__XX____};

/* Start of unicode area <Halfwidth and Fullwidth Forms> */
GUI_CONST_STORAGE unsigned char acGUI_FontCNFonts_FF1A[ 10] = { /* code FF1A, FULLWIDTH COLON */
  XXX_____,
  XXX_____,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XXX_____,
  XXX_____};

GUI_CONST_STORAGE GUI_CHARINFO_EXT GUI_FontCNFonts_CharInfo[78] = {
   {  10,  14,   1,   4,  12, acGUI_FontCNFonts_0025 } /* code 0025, PERCENT SIGN */
  ,{  10,  11,   1,   5,  12, acGUI_FontCNFonts_002B } /* code 002B, PLUS SIGN */
  ,{  10,   1,   1,  10,  12, acGUI_FontCNFonts_002D } /* code 002D, HYPHEN-MINUS */
  ,{   3,   2,   1,  16,  12, acGUI_FontCNFonts_002E } /* code 002E, FULL STOP */
  ,{  10,  18,   1,   2,  12, acGUI_FontCNFonts_002F } /* code 002F, SOLIDUS */
  ,{   9,  14,   1,   4,  12, acGUI_FontCNFonts_0030 } /* code 0030, DIGIT ZERO */
  ,{   6,  14,   3,   4,  12, acGUI_FontCNFonts_0031 } /* code 0031, DIGIT ONE */
  ,{   9,  14,   1,   4,  12, acGUI_FontCNFonts_0032 } /* code 0032, DIGIT TWO */
  ,{   9,  14,   1,   4,  12, acGUI_FontCNFonts_0033 } /* code 0033, DIGIT THREE */
  ,{  10,  15,   1,   3,  12, acGUI_FontCNFonts_0034 } /* code 0034, DIGIT FOUR */
  ,{   9,  14,   1,   4,  12, acGUI_FontCNFonts_0035 } /* code 0035, DIGIT FIVE */
  ,{   9,  14,   1,   4,  12, acGUI_FontCNFonts_0036 } /* code 0036, DIGIT SIX */
  ,{   9,  14,   1,   4,  12, acGUI_FontCNFonts_0037 } /* code 0037, DIGIT SEVEN */
  ,{   9,  14,   1,   4,  12, acGUI_FontCNFonts_0038 } /* code 0038, DIGIT EIGHT */
  ,{   9,  14,   1,   4,  12, acGUI_FontCNFonts_0039 } /* code 0039, DIGIT NINE */
  ,{   3,  10,   4,   8,  12, acGUI_FontCNFonts_003A } /* code 003A, COLON */
  ,{  21,  19,   0,   2,  23, acGUI_FontCNFonts_4E0D } /* code 4E0D */
  ,{  22,  20,   0,   1,  23, acGUI_FontCNFonts_4F4D } /* code 4F4D */
  ,{  22,  20,   0,   1,  23, acGUI_FontCNFonts_4FDD } /* code 4FDD */
  ,{  22,  20,   0,   1,  23, acGUI_FontCNFonts_503C } /* code 503C */
  ,{  21,  20,   0,   1,  23, acGUI_FontCNFonts_505C } /* code 505C */
  ,{  20,  20,   1,   1,  23, acGUI_FontCNFonts_5173 } /* code 5173 */
  ,{  21,  20,   1,   1,  23, acGUI_FontCNFonts_51BB } /* code 51BB */
  ,{  22,  20,   0,   1,  23, acGUI_FontCNFonts_5206 } /* code 5206 */
  ,{  20,  20,   1,   1,  23, acGUI_FontCNFonts_524D } /* code 524D */
  ,{  19,  20,   1,   1,  23, acGUI_FontCNFonts_529B } /* code 529B */
  ,{  21,  20,   0,   1,  23, acGUI_FontCNFonts_52A8 } /* code 52A8 */
  ,{  20,  18,   1,   3,  23, acGUI_FontCNFonts_538B } /* code 538B */
  ,{  21,  19,   1,   2,  23, acGUI_FontCNFonts_540E } /* code 540E */
  ,{  20,  20,   0,   1,  23, acGUI_FontCNFonts_542F } /* code 542F */
  ,{  21,  20,   1,   1,  23, acGUI_FontCNFonts_5439 } /* code 5439 */
  ,{  22,  20,   0,   1,  23, acGUI_FontCNFonts_5B9A } /* code 5B9A */
  ,{  20,  20,   1,   1,  23, acGUI_FontCNFonts_5E38 } /* code 5E38 */
  ,{  20,  20,   1,   1,  23, acGUI_FontCNFonts_5E74 } /* code 5E74 */
  ,{  22,  20,   0,   1,  23, acGUI_FontCNFonts_5EA6 } /* code 5EA6 */
  ,{  22,  19,   0,   2,  23, acGUI_FontCNFonts_5F00 } /* code 5F00 */
  ,{  19,  20,   1,   1,  23, acGUI_FontCNFonts_5F15 } /* code 5F15 */
  ,{  21,  20,   0,   1,  23, acGUI_FontCNFonts_5F85 } /* code 5F85 */
  ,{  22,  20,   0,   1,  23, acGUI_FontCNFonts_6001 } /* code 6001 */
  ,{  22,  20,   0,   1,  23, acGUI_FontCNFonts_62A5 } /* code 62A5 */
  ,{  22,  20,   0,   1,  23, acGUI_FontCNFonts_6599 } /* code 6599 */
  ,{  16,  17,   3,   3,  23, acGUI_FontCNFonts_65E5 } /* code 65E5 */
  ,{  20,  19,   2,   2,  23, acGUI_FontCNFonts_65F6 } /* code 65F6 */
  ,{  20,  19,   1,   2,  23, acGUI_FontCNFonts_661F } /* code 661F */
  ,{  19,  19,   0,   2,  23, acGUI_FontCNFonts_6708 } /* code 6708 */
  ,{  19,  19,   1,   2,  23, acGUI_FontCNFonts_671F } /* code 671F */
  ,{  22,  20,   0,   1,  23, acGUI_FontCNFonts_673A } /* code 673A */
  ,{  21,  18,   1,   2,  23, acGUI_FontCNFonts_6B62 } /* code 6B62 */
  ,{  22,  17,   0,   3,  23, acGUI_FontCNFonts_6B63 } /* code 6B63 */
  ,{  20,  20,   1,   1,  23, acGUI_FontCNFonts_6C34 } /* code 6C34 */
  ,{  20,  19,   1,   2,  23, acGUI_FontCNFonts_6CF5 } /* code 6CF5 */
  ,{  22,  19,   0,   2,  23, acGUI_FontCNFonts_6E29 } /* code 6E29 */
  ,{  22,  20,   0,   1,  23, acGUI_FontCNFonts_6EDE } /* code 6EDE */
  ,{  21,  20,   1,   1,  23, acGUI_FontCNFonts_706B } /* code 706B */
  ,{  20,  20,   1,   1,  23, acGUI_FontCNFonts_70B9 } /* code 70B9 */
  ,{  21,  20,   0,   1,  23, acGUI_FontCNFonts_70ED } /* code 70ED */
  ,{  22,  20,   0,   1,  23, acGUI_FontCNFonts_72B6 } /* code 72B6 */
  ,{  21,  20,   0,   1,  23, acGUI_FontCNFonts_79D2 } /* code 79D2 */
  ,{  19,  20,   1,   1,  23, acGUI_FontCNFonts_7CFB } /* code 7CFB */
  ,{  21,  20,   0,   1,  23, acGUI_FontCNFonts_7EDF } /* code 7EDF */
  ,{  22,  18,   0,   2,  23, acGUI_FontCNFonts_7F6E } /* code 7F6E */
  ,{  22,  20,   0,   1,  23, acGUI_FontCNFonts_884C } /* code 884C */
  ,{  21,  20,   1,   1,  23, acGUI_FontCNFonts_8B66 } /* code 8B66 */
  ,{  22,  19,   0,   2,  23, acGUI_FontCNFonts_8BBE } /* code 8BBE */
  ,{  22,  20,   0,   1,  23, acGUI_FontCNFonts_8D85 } /* code 8D85 */
  ,{  21,  19,   0,   2,  23, acGUI_FontCNFonts_8DB3 } /* code 8DB3 */
  ,{  22,  19,   0,   2,  23, acGUI_FontCNFonts_8FD0 } /* code 8FD0 */
  ,{  22,  20,   0,   1,  23, acGUI_FontCNFonts_8FDB } /* code 8FDB */
  ,{  21,  19,   1,   2,  23, acGUI_FontCNFonts_9001 } /* code 9001 */
  ,{  18,  20,   2,   1,  23, acGUI_FontCNFonts_95F4 } /* code 95F4 */
  ,{  19,  20,   1,   1,  23, acGUI_FontCNFonts_9608 } /* code 9608 */
  ,{  21,  20,   1,   1,  23, acGUI_FontCNFonts_9632 } /* code 9632 */
  ,{  19,  20,   2,   1,  23, acGUI_FontCNFonts_9636 } /* code 9636 */
  ,{  19,  19,   2,   2,  23, acGUI_FontCNFonts_9694 } /* code 9694 */
  ,{  21,  19,   0,   2,  23, acGUI_FontCNFonts_9884 } /* code 9884 */
  ,{  21,  19,   1,   2,  23, acGUI_FontCNFonts_98CE } /* code 98CE */
  ,{  20,  20,   1,   1,  23, acGUI_FontCNFonts_9F13 } /* code 9F13 */
  ,{   3,  10,   5,   9,  23, acGUI_FontCNFonts_FF1A } /* code FF1A, FULLWIDTH COLON */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontCNFonts_Prop64 = {
   0xFF1A /* first character */
  ,0xFF1A /* last character  */
  ,&GUI_FontCNFonts_CharInfo[ 77] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP_EXT *)0 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontCNFonts_Prop63 = {
   0x9F13 /* first character */
  ,0x9F13 /* last character  */
  ,&GUI_FontCNFonts_CharInfo[ 76] /* address of first character */
  ,&GUI_FontCNFonts_Prop64 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontCNFonts_Prop62 = {
   0x98CE /* first character */
  ,0x98CE /* last character  */
  ,&GUI_FontCNFonts_CharInfo[ 75] /* address of first character */
  ,&GUI_FontCNFonts_Prop63 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontCNFonts_Prop61 = {
   0x9884 /* first character */
  ,0x9884 /* last character  */
  ,&GUI_FontCNFonts_CharInfo[ 74] /* address of first character */
  ,&GUI_FontCNFonts_Prop62 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontCNFonts_Prop60 = {
   0x9694 /* first character */
  ,0x9694 /* last character  */
  ,&GUI_FontCNFonts_CharInfo[ 73] /* address of first character */
  ,&GUI_FontCNFonts_Prop61 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontCNFonts_Prop59 = {
   0x9636 /* first character */
  ,0x9636 /* last character  */
  ,&GUI_FontCNFonts_CharInfo[ 72] /* address of first character */
  ,&GUI_FontCNFonts_Prop60 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontCNFonts_Prop58 = {
   0x9632 /* first character */
  ,0x9632 /* last character  */
  ,&GUI_FontCNFonts_CharInfo[ 71] /* address of first character */
  ,&GUI_FontCNFonts_Prop59 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontCNFonts_Prop57 = {
   0x9608 /* first character */
  ,0x9608 /* last character  */
  ,&GUI_FontCNFonts_CharInfo[ 70] /* address of first character */
  ,&GUI_FontCNFonts_Prop58 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontCNFonts_Prop56 = {
   0x95F4 /* first character */
  ,0x95F4 /* last character  */
  ,&GUI_FontCNFonts_CharInfo[ 69] /* address of first character */
  ,&GUI_FontCNFonts_Prop57 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontCNFonts_Prop55 = {
   0x9001 /* first character */
  ,0x9001 /* last character  */
  ,&GUI_FontCNFonts_CharInfo[ 68] /* address of first character */
  ,&GUI_FontCNFonts_Prop56 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontCNFonts_Prop54 = {
   0x8FDB /* first character */
  ,0x8FDB /* last character  */
  ,&GUI_FontCNFonts_CharInfo[ 67] /* address of first character */
  ,&GUI_FontCNFonts_Prop55 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontCNFonts_Prop53 = {
   0x8FD0 /* first character */
  ,0x8FD0 /* last character  */
  ,&GUI_FontCNFonts_CharInfo[ 66] /* address of first character */
  ,&GUI_FontCNFonts_Prop54 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontCNFonts_Prop52 = {
   0x8DB3 /* first character */
  ,0x8DB3 /* last character  */
  ,&GUI_FontCNFonts_CharInfo[ 65] /* address of first character */
  ,&GUI_FontCNFonts_Prop53 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontCNFonts_Prop51 = {
   0x8D85 /* first character */
  ,0x8D85 /* last character  */
  ,&GUI_FontCNFonts_CharInfo[ 64] /* address of first character */
  ,&GUI_FontCNFonts_Prop52 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontCNFonts_Prop50 = {
   0x8BBE /* first character */
  ,0x8BBE /* last character  */
  ,&GUI_FontCNFonts_CharInfo[ 63] /* address of first character */
  ,&GUI_FontCNFonts_Prop51 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontCNFonts_Prop49 = {
   0x8B66 /* first character */
  ,0x8B66 /* last character  */
  ,&GUI_FontCNFonts_CharInfo[ 62] /* address of first character */
  ,&GUI_FontCNFonts_Prop50 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontCNFonts_Prop48 = {
   0x884C /* first character */
  ,0x884C /* last character  */
  ,&GUI_FontCNFonts_CharInfo[ 61] /* address of first character */
  ,&GUI_FontCNFonts_Prop49 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontCNFonts_Prop47 = {
   0x7F6E /* first character */
  ,0x7F6E /* last character  */
  ,&GUI_FontCNFonts_CharInfo[ 60] /* address of first character */
  ,&GUI_FontCNFonts_Prop48 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontCNFonts_Prop46 = {
   0x7EDF /* first character */
  ,0x7EDF /* last character  */
  ,&GUI_FontCNFonts_CharInfo[ 59] /* address of first character */
  ,&GUI_FontCNFonts_Prop47 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontCNFonts_Prop45 = {
   0x7CFB /* first character */
  ,0x7CFB /* last character  */
  ,&GUI_FontCNFonts_CharInfo[ 58] /* address of first character */
  ,&GUI_FontCNFonts_Prop46 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontCNFonts_Prop44 = {
   0x79D2 /* first character */
  ,0x79D2 /* last character  */
  ,&GUI_FontCNFonts_CharInfo[ 57] /* address of first character */
  ,&GUI_FontCNFonts_Prop45 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontCNFonts_Prop43 = {
   0x72B6 /* first character */
  ,0x72B6 /* last character  */
  ,&GUI_FontCNFonts_CharInfo[ 56] /* address of first character */
  ,&GUI_FontCNFonts_Prop44 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontCNFonts_Prop42 = {
   0x70ED /* first character */
  ,0x70ED /* last character  */
  ,&GUI_FontCNFonts_CharInfo[ 55] /* address of first character */
  ,&GUI_FontCNFonts_Prop43 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontCNFonts_Prop41 = {
   0x70B9 /* first character */
  ,0x70B9 /* last character  */
  ,&GUI_FontCNFonts_CharInfo[ 54] /* address of first character */
  ,&GUI_FontCNFonts_Prop42 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontCNFonts_Prop40 = {
   0x706B /* first character */
  ,0x706B /* last character  */
  ,&GUI_FontCNFonts_CharInfo[ 53] /* address of first character */
  ,&GUI_FontCNFonts_Prop41 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontCNFonts_Prop39 = {
   0x6EDE /* first character */
  ,0x6EDE /* last character  */
  ,&GUI_FontCNFonts_CharInfo[ 52] /* address of first character */
  ,&GUI_FontCNFonts_Prop40 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontCNFonts_Prop38 = {
   0x6E29 /* first character */
  ,0x6E29 /* last character  */
  ,&GUI_FontCNFonts_CharInfo[ 51] /* address of first character */
  ,&GUI_FontCNFonts_Prop39 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontCNFonts_Prop37 = {
   0x6CF5 /* first character */
  ,0x6CF5 /* last character  */
  ,&GUI_FontCNFonts_CharInfo[ 50] /* address of first character */
  ,&GUI_FontCNFonts_Prop38 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontCNFonts_Prop36 = {
   0x6C34 /* first character */
  ,0x6C34 /* last character  */
  ,&GUI_FontCNFonts_CharInfo[ 49] /* address of first character */
  ,&GUI_FontCNFonts_Prop37 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontCNFonts_Prop35 = {
   0x6B62 /* first character */
  ,0x6B63 /* last character  */
  ,&GUI_FontCNFonts_CharInfo[ 47] /* address of first character */
  ,&GUI_FontCNFonts_Prop36 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontCNFonts_Prop34 = {
   0x673A /* first character */
  ,0x673A /* last character  */
  ,&GUI_FontCNFonts_CharInfo[ 46] /* address of first character */
  ,&GUI_FontCNFonts_Prop35 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontCNFonts_Prop33 = {
   0x671F /* first character */
  ,0x671F /* last character  */
  ,&GUI_FontCNFonts_CharInfo[ 45] /* address of first character */
  ,&GUI_FontCNFonts_Prop34 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontCNFonts_Prop32 = {
   0x6708 /* first character */
  ,0x6708 /* last character  */
  ,&GUI_FontCNFonts_CharInfo[ 44] /* address of first character */
  ,&GUI_FontCNFonts_Prop33 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontCNFonts_Prop31 = {
   0x661F /* first character */
  ,0x661F /* last character  */
  ,&GUI_FontCNFonts_CharInfo[ 43] /* address of first character */
  ,&GUI_FontCNFonts_Prop32 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontCNFonts_Prop30 = {
   0x65F6 /* first character */
  ,0x65F6 /* last character  */
  ,&GUI_FontCNFonts_CharInfo[ 42] /* address of first character */
  ,&GUI_FontCNFonts_Prop31 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontCNFonts_Prop29 = {
   0x65E5 /* first character */
  ,0x65E5 /* last character  */
  ,&GUI_FontCNFonts_CharInfo[ 41] /* address of first character */
  ,&GUI_FontCNFonts_Prop30 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontCNFonts_Prop28 = {
   0x6599 /* first character */
  ,0x6599 /* last character  */
  ,&GUI_FontCNFonts_CharInfo[ 40] /* address of first character */
  ,&GUI_FontCNFonts_Prop29 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontCNFonts_Prop27 = {
   0x62A5 /* first character */
  ,0x62A5 /* last character  */
  ,&GUI_FontCNFonts_CharInfo[ 39] /* address of first character */
  ,&GUI_FontCNFonts_Prop28 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontCNFonts_Prop26 = {
   0x6001 /* first character */
  ,0x6001 /* last character  */
  ,&GUI_FontCNFonts_CharInfo[ 38] /* address of first character */
  ,&GUI_FontCNFonts_Prop27 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontCNFonts_Prop25 = {
   0x5F85 /* first character */
  ,0x5F85 /* last character  */
  ,&GUI_FontCNFonts_CharInfo[ 37] /* address of first character */
  ,&GUI_FontCNFonts_Prop26 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontCNFonts_Prop24 = {
   0x5F15 /* first character */
  ,0x5F15 /* last character  */
  ,&GUI_FontCNFonts_CharInfo[ 36] /* address of first character */
  ,&GUI_FontCNFonts_Prop25 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontCNFonts_Prop23 = {
   0x5F00 /* first character */
  ,0x5F00 /* last character  */
  ,&GUI_FontCNFonts_CharInfo[ 35] /* address of first character */
  ,&GUI_FontCNFonts_Prop24 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontCNFonts_Prop22 = {
   0x5EA6 /* first character */
  ,0x5EA6 /* last character  */
  ,&GUI_FontCNFonts_CharInfo[ 34] /* address of first character */
  ,&GUI_FontCNFonts_Prop23 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontCNFonts_Prop21 = {
   0x5E74 /* first character */
  ,0x5E74 /* last character  */
  ,&GUI_FontCNFonts_CharInfo[ 33] /* address of first character */
  ,&GUI_FontCNFonts_Prop22 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontCNFonts_Prop20 = {
   0x5E38 /* first character */
  ,0x5E38 /* last character  */
  ,&GUI_FontCNFonts_CharInfo[ 32] /* address of first character */
  ,&GUI_FontCNFonts_Prop21 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontCNFonts_Prop19 = {
   0x5B9A /* first character */
  ,0x5B9A /* last character  */
  ,&GUI_FontCNFonts_CharInfo[ 31] /* address of first character */
  ,&GUI_FontCNFonts_Prop20 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontCNFonts_Prop18 = {
   0x5439 /* first character */
  ,0x5439 /* last character  */
  ,&GUI_FontCNFonts_CharInfo[ 30] /* address of first character */
  ,&GUI_FontCNFonts_Prop19 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontCNFonts_Prop17 = {
   0x542F /* first character */
  ,0x542F /* last character  */
  ,&GUI_FontCNFonts_CharInfo[ 29] /* address of first character */
  ,&GUI_FontCNFonts_Prop18 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontCNFonts_Prop16 = {
   0x540E /* first character */
  ,0x540E /* last character  */
  ,&GUI_FontCNFonts_CharInfo[ 28] /* address of first character */
  ,&GUI_FontCNFonts_Prop17 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontCNFonts_Prop15 = {
   0x538B /* first character */
  ,0x538B /* last character  */
  ,&GUI_FontCNFonts_CharInfo[ 27] /* address of first character */
  ,&GUI_FontCNFonts_Prop16 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontCNFonts_Prop14 = {
   0x52A8 /* first character */
  ,0x52A8 /* last character  */
  ,&GUI_FontCNFonts_CharInfo[ 26] /* address of first character */
  ,&GUI_FontCNFonts_Prop15 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontCNFonts_Prop13 = {
   0x529B /* first character */
  ,0x529B /* last character  */
  ,&GUI_FontCNFonts_CharInfo[ 25] /* address of first character */
  ,&GUI_FontCNFonts_Prop14 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontCNFonts_Prop12 = {
   0x524D /* first character */
  ,0x524D /* last character  */
  ,&GUI_FontCNFonts_CharInfo[ 24] /* address of first character */
  ,&GUI_FontCNFonts_Prop13 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontCNFonts_Prop11 = {
   0x5206 /* first character */
  ,0x5206 /* last character  */
  ,&GUI_FontCNFonts_CharInfo[ 23] /* address of first character */
  ,&GUI_FontCNFonts_Prop12 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontCNFonts_Prop10 = {
   0x51BB /* first character */
  ,0x51BB /* last character  */
  ,&GUI_FontCNFonts_CharInfo[ 22] /* address of first character */
  ,&GUI_FontCNFonts_Prop11 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontCNFonts_Prop9 = {
   0x5173 /* first character */
  ,0x5173 /* last character  */
  ,&GUI_FontCNFonts_CharInfo[ 21] /* address of first character */
  ,&GUI_FontCNFonts_Prop10 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontCNFonts_Prop8 = {
   0x505C /* first character */
  ,0x505C /* last character  */
  ,&GUI_FontCNFonts_CharInfo[ 20] /* address of first character */
  ,&GUI_FontCNFonts_Prop9 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontCNFonts_Prop7 = {
   0x503C /* first character */
  ,0x503C /* last character  */
  ,&GUI_FontCNFonts_CharInfo[ 19] /* address of first character */
  ,&GUI_FontCNFonts_Prop8 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontCNFonts_Prop6 = {
   0x4FDD /* first character */
  ,0x4FDD /* last character  */
  ,&GUI_FontCNFonts_CharInfo[ 18] /* address of first character */
  ,&GUI_FontCNFonts_Prop7 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontCNFonts_Prop5 = {
   0x4F4D /* first character */
  ,0x4F4D /* last character  */
  ,&GUI_FontCNFonts_CharInfo[ 17] /* address of first character */
  ,&GUI_FontCNFonts_Prop6 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontCNFonts_Prop4 = {
   0x4E0D /* first character */
  ,0x4E0D /* last character  */
  ,&GUI_FontCNFonts_CharInfo[ 16] /* address of first character */
  ,&GUI_FontCNFonts_Prop5 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontCNFonts_Prop3 = {
   0x002D /* first character */
  ,0x003A /* last character  */
  ,&GUI_FontCNFonts_CharInfo[  2] /* address of first character */
  ,&GUI_FontCNFonts_Prop4 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontCNFonts_Prop2 = {
   0x002B /* first character */
  ,0x002B /* last character  */
  ,&GUI_FontCNFonts_CharInfo[  1] /* address of first character */
  ,&GUI_FontCNFonts_Prop3 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontCNFonts_Prop1 = {
   0x0025 /* first character */
  ,0x0025 /* last character  */
  ,&GUI_FontCNFonts_CharInfo[  0] /* address of first character */
  ,&GUI_FontCNFonts_Prop2 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT GUI_FontCNFonts = {
   GUI_FONTTYPE_PROP_EXT /* type of font    */
  ,21 /* height of font  */
  ,21 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_FontCNFonts_Prop1}
  ,18 /* Baseline */
  ,9 /* Height of lowercase characters */
  ,14 /* Height of capital characters */
};

